# Generated by Django 4.2.5 on 2023-11-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='produer',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_price',
        ),
    ]
