export const PROFILE_DETAILS_REQUEST = 'PROFILE_DETAILS_REQUEST'
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS'
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL'
export const PROFILE_DETAILS_REST = 'PROFILE_DETAILS_REST'

export const PROFILE_UPDATE_DETAILS_REQUEST = 'PROFILE_UPDATE_DETAILS_REQUEST'
export const PROFILE_UPDATE_DETAILS_SUCCESS = 'PROFILE_UPDATE_DETAILS_SUCCESS'
export const PROFILE_UPDATE_DETAILS_FAIL = 'PROFILE_UPDATE_DETAILS_FAIL'
export const PROFILE_UPDATE_DETAILS_RESET = 'PROFILE_UPDATE_DETAILS_RESET'

export const USER_CHANGE_PASSWORD_REQUEST = 'USER_CHANGE_PASSWORD_REQUEST'
export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS'
export const USER_CHANGE_PASSWORD_FAIL = 'USER_CHANGE_PASSWORD_FAIL'
export const USER_CHANGE_PASSWORD_REST = 'USER_CHANGE_PASSWORD_REST'